application: malenah-portal
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /css
  static_dir: assets/css
- url: /.*
  script: main.application
- url: .*
  script: main.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
