application: malenah-android
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: main.application
- url: .*  # directs all routes to main.app
  script: main.application

#App Engine SDK libs
libraries:
- name: webapp2
  version: latest
